[package]
name = "op-rbuilder-node-optimism"
edition = "2021"

[dependencies]
# workspace
op-rbuilder-payload-builder = { path = "../payload_builder" }
transaction-pool-bundle-ext = { path = "../../transaction-pool-bundle-ext" }
rbuilder-bundle-pool-operations = { path = "../../transaction-pool-bundle-ext/bundle_pool_ops/rbuilder" }

# reth
reth-payload-builder.workspace = true
reth-primitives.workspace = true
reth-basic-payload-builder.workspace = true
reth-node-builder.workspace = true
reth-node-api.workspace = true
reth-trie-db.workspace = true
reth-tracing.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-evm.workspace = true
reth-optimism-evm.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-node = { workspace = true }
reth-payload-primitives.workspace = true
reth-tasks.workspace = true
reth-revm.workspace = true
reth-chain-state.workspace = true
reth-chainspec.workspace = true
reth-execution-types.workspace = true
reth-optimism-consensus.workspace = true
reth-optimism-payload-builder.workspace = true
reth-optimism-forks.workspace = true
reth-trie.workspace = true
revm.workspace = true

alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-rpc-types-beacon.workspace = true
alloy-consensus.workspace = true
op-alloy-consensus.workspace = true

tokio.workspace = true
futures-util = "0.3.31"
oneshot = "0.1.8"

# async
tracing.workspace = true

# misc
clap.workspace = true
eyre.workspace = true

[features]
optimism = [
	"rbuilder-bundle-pool-operations/optimism",
	"reth-optimism-evm/optimism",
	"reth-optimism-node/optimism",
	"reth-primitives/optimism",
	"reth-provider/optimism",
	"op-rbuilder-payload-builder/optimism"
]
