log_level = "info,rbuilder=debug"

chain = "mainnet"
reth_datadir = "/mnt/data/reth"

backtest_fetch_eth_rpc_url = "http://127.0.0.1:8545"
backtest_fetch_eth_rpc_parallel = 400
backtest_fetch_output_file = "~/.rbuilder/backtest/main.sqlite"
backtest_fetch_mempool_data_dir = "~/.rbuilder/mempool-data"

sbundle_mergeabe_signers = []

backtest_builders = ["mp-ordering", "mgp-ordering"]

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true

