# rbuilder commit (on develop branch) up to fefbedbe6bbb1751c967da699342dfd821101a4c
log_json = false
log_level = "info,rbuilder=debug"
#log_file_path = "<project path>/preconf-builder/logs/rbuilder.log"

#redacted_telemetry_server_port = 6061
#redacted_telemetry_server_ip = "0.0.0.0"
#full_telemetry_server_port = 6060
#full_telemetry_server_ip = "0.0.0.0"

chain = "<.playground path>/devnet/genesis.json"
reth_datadir = "<.playground path>/devnet/data_reth"

### address: 0x0fD5C0C300b9075D62406dA142ab4bBAAC908AeD
coinbase_secret_key = "env:COINBASE_SECRET_KEY"
relay_secret_key = "env:RELAY_SECRET_KEY"
optimistic_relay_secret_key = "env:OPTIMISTIC_RELAY_SECRET_KEY"

# cl_node_url can be a single value, array of values, or passed by an environment variables with values separated with a comma
# mock "http://localhost:3500", devnet "http://18.163.111.239:3500"
cl_node_url = ["env:CL_NODE_URL"]
jsonrpc_server_port = 8645
jsonrpc_server_ip = "0.0.0.0"
# mock "<.playground path>/devnet/reth.ipc", devnet "/reth-ipc/reth-ipc.ipc"
el_node_ipc_path = "<.playground path>/devnet/reth.ipc"
extra_data = "ETHGas www.ethgas.com"

#blocklist_file_path = "./blocklist.json"

ignore_cancellable_orders = false

# watchdog_timeout_sec = 600
# simulation_threads = 1

# genesis_fork_version = "0x00112233"

sbundle_mergeabe_signers = []
live_builders = ["preconf-ordering"]

enabled_relays = ["custom"]

# EthGas API domain
# mock server: "http://localhost:3210", exchange: https://uatapp.ethgas.com, https://testapp.ethgas.com
preconf_api_url = "https://devapp.ethgas.com"
# EthGas WebSocket domain
# exchange: wss://uatapp.ethgas.com/ws, wss://testapp.ethgas.com/ws
preconf_ws_url = "wss://devapp.ethgas.com/ws"
fallback_fee_recipient = "0x0fD5C0C300b9075D62406dA142ab4bBAAC908AeD"

[[relays]]
name = "custom"
url = "http://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@localhost:5555"
priority = 0
use_ssz_for_submit = false
use_gzip_for_submit = false

[[builders]]
name = "preconf-ordering"
algo = "ordering-builder"
discard_txs = false
coinbase_payment = true
sorting = "preconf"
failed_order_retries = 1
drop_failed_orders = true
build_duration_deadline_ms = 1500

#[[builders]]
#name = "mgp-ordering"
#algo = "ordering-builder"
#discard_txs = true
#sorting = "mev-gas-price"
#failed_order_retries = 1
#drop_failed_orders = true
#
#[[builders]]
#name = "mp-ordering"
#algo = "ordering-builder"
#discard_txs = true
#sorting = "max-profit"
#failed_order_retries = 1
#drop_failed_orders = true
#coinbase_payment = false