// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MustWinBlockParams {
    #[prost(uint64, tag = "1")]
    pub block: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DestroySlotBidderParams {
    #[prost(uint64, tag = "1")]
    pub session_id: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSlotBidderParams {
    #[prost(uint64, tag = "1")]
    pub block: u64,
    #[prost(uint64, tag = "2")]
    pub slot: u64,
    /// Array of 32 bytes
    #[prost(bytes = "vec", tag = "3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    /// Id identifying the session. Used in all following calls.
    #[prost(uint64, tag = "4")]
    pub session_id: u64,
    /// unix ts
    #[prost(int64, tag = "5")]
    pub slot_timestamp: i64,
}
/// Info about a onchain block from reth.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LandedBlockInfo {
    #[prost(uint64, tag = "1")]
    pub block_number: u64,
    #[prost(int64, tag = "2")]
    pub block_timestamp: i64,
    /// Array of 4 uint64
    #[prost(uint64, repeated, tag = "3")]
    pub builder_balance: ::prost::alloc::vec::Vec<u64>,
    /// true -> we landed this block.
    /// If false we could have landed it in coinbase == fee recipient mode but balance wouldn't change so we don't care.
    #[prost(bool, tag = "4")]
    pub beneficiary_is_builder: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LandedBlocksParams {
    #[prost(message, repeated, tag = "1")]
    pub landed_block_info: ::prost::alloc::vec::Vec<LandedBlockInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelaySet {
    /// Ids of the relays (MevBoostRelayIDs)
    #[prost(string, repeated, tag = "2")]
    pub relay_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitParams {
    #[prost(message, repeated, tag = "1")]
    pub landed_block_info: ::prost::alloc::vec::Vec<LandedBlockInfo>,
    /// All the relays we bid to.
    #[prost(message, optional, tag = "2")]
    pub all_relay_ids: ::core::option::Option<RelaySet>,
}
/// Mapping of build_info::Version
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BidderVersionInfo {
    #[prost(string, tag = "1")]
    pub git_commit: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub git_ref: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub build_time_utc: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitReturn {
    #[prost(message, optional, tag = "1")]
    pub bidder_version: ::core::option::Option<BidderVersionInfo>,
    /// RelaySets the bidder will use.
    #[prost(message, repeated, tag = "2")]
    pub relay_sets: ::prost::alloc::vec::Vec<RelaySet>,
}
/// Generated client implementations.
pub mod bidding_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Protocol for the bidding service. It's used to marshal all the traits in src/block_descriptor_bidding/traits.rs
    /// Usage:
    /// The client connects to the server and calls Initialize, this call should create the real BiddingService on the server side.
    /// Before calling Initialize any other call will fail. Initialize can be called again to recreate the BiddingService (eg: rbuilder reconnection).
    /// After that, for each slot the client should call CreateSlotBidder to create the SlotBidder on the server side and DestroySlotBidder when the SlotBidder is not needed anymore.
    /// Other calls are almost 1 to 1 with the original traits but for SlotBidder calls block/slot are added to identify the SlotBidder.
    /// Notice that CreateSlotBidder returns a stream of Callback. This stream is used for 2 things:
    /// - Send back bids made by the SlotBidder.
    /// - Notify changes on the state of SlotBidder's can_use_suggested_fee_recipient_as_coinbase. We use this methodology instead of a
    ///   forward RPC call since can_use_suggested_fee_recipient_as_coinbase almost does not change and we want to avoid innecesary RPC calls during block building.
    #[derive(Debug, Clone)]
    pub struct BiddingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BiddingServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BiddingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BiddingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            BiddingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Call after connection before calling anything. This will really create the BiddingService on the server side.
        /// Returns the version info for the server side.
        pub async fn initialize(
            &mut self,
            request: impl tonic::IntoRequest<super::InitParams>,
        ) -> std::result::Result<tonic::Response<super::InitReturn>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/Initialize",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("bidding_service.BiddingService", "Initialize"));
            self.inner.unary(req, path, codec).await
        }
        /// BiddingService
        pub async fn create_slot_bidder(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSlotBidderParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/CreateSlotBidder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bidding_service.BiddingService", "CreateSlotBidder"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn destroy_slot_bidder(
            &mut self,
            request: impl tonic::IntoRequest<super::DestroySlotBidderParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/DestroySlotBidder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bidding_service.BiddingService",
                        "DestroySlotBidder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn must_win_block(
            &mut self,
            request: impl tonic::IntoRequest<super::MustWinBlockParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/MustWinBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("bidding_service.BiddingService", "MustWinBlock"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_new_landed_blocks_detected(
            &mut self,
            request: impl tonic::IntoRequest<super::LandedBlocksParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/UpdateNewLandedBlocksDetected",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bidding_service.BiddingService",
                        "UpdateNewLandedBlocksDetected",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_failed_reading_new_landed_blocks(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bidding_service.BiddingService/UpdateFailedReadingNewLandedBlocks",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bidding_service.BiddingService",
                        "UpdateFailedReadingNewLandedBlocks",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod bidding_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with BiddingServiceServer.
    #[async_trait]
    pub trait BiddingService: std::marker::Send + std::marker::Sync + 'static {
        /// Call after connection before calling anything. This will really create the BiddingService on the server side.
        /// Returns the version info for the server side.
        async fn initialize(
            &self,
            request: tonic::Request<super::InitParams>,
        ) -> std::result::Result<tonic::Response<super::InitReturn>, tonic::Status>;
        /// BiddingService
        async fn create_slot_bidder(
            &self,
            request: tonic::Request<super::CreateSlotBidderParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn destroy_slot_bidder(
            &self,
            request: tonic::Request<super::DestroySlotBidderParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn must_win_block(
            &self,
            request: tonic::Request<super::MustWinBlockParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn update_new_landed_blocks_detected(
            &self,
            request: tonic::Request<super::LandedBlocksParams>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn update_failed_reading_new_landed_blocks(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
    }
    /// Protocol for the bidding service. It's used to marshal all the traits in src/block_descriptor_bidding/traits.rs
    /// Usage:
    /// The client connects to the server and calls Initialize, this call should create the real BiddingService on the server side.
    /// Before calling Initialize any other call will fail. Initialize can be called again to recreate the BiddingService (eg: rbuilder reconnection).
    /// After that, for each slot the client should call CreateSlotBidder to create the SlotBidder on the server side and DestroySlotBidder when the SlotBidder is not needed anymore.
    /// Other calls are almost 1 to 1 with the original traits but for SlotBidder calls block/slot are added to identify the SlotBidder.
    /// Notice that CreateSlotBidder returns a stream of Callback. This stream is used for 2 things:
    /// - Send back bids made by the SlotBidder.
    /// - Notify changes on the state of SlotBidder's can_use_suggested_fee_recipient_as_coinbase. We use this methodology instead of a
    ///   forward RPC call since can_use_suggested_fee_recipient_as_coinbase almost does not change and we want to avoid innecesary RPC calls during block building.
    #[derive(Debug)]
    pub struct BiddingServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> BiddingServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for BiddingServiceServer<T>
    where
        T: BiddingService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/bidding_service.BiddingService/Initialize" => {
                    #[allow(non_camel_case_types)]
                    struct InitializeSvc<T: BiddingService>(pub Arc<T>);
                    impl<
                        T: BiddingService,
                    > tonic::server::UnaryService<super::InitParams>
                    for InitializeSvc<T> {
                        type Response = super::InitReturn;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InitParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::initialize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = InitializeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bidding_service.BiddingService/CreateSlotBidder" => {
                    #[allow(non_camel_case_types)]
                    struct CreateSlotBidderSvc<T: BiddingService>(pub Arc<T>);
                    impl<
                        T: BiddingService,
                    > tonic::server::UnaryService<super::CreateSlotBidderParams>
                    for CreateSlotBidderSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateSlotBidderParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::create_slot_bidder(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateSlotBidderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bidding_service.BiddingService/DestroySlotBidder" => {
                    #[allow(non_camel_case_types)]
                    struct DestroySlotBidderSvc<T: BiddingService>(pub Arc<T>);
                    impl<
                        T: BiddingService,
                    > tonic::server::UnaryService<super::DestroySlotBidderParams>
                    for DestroySlotBidderSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DestroySlotBidderParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::destroy_slot_bidder(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DestroySlotBidderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bidding_service.BiddingService/MustWinBlock" => {
                    #[allow(non_camel_case_types)]
                    struct MustWinBlockSvc<T: BiddingService>(pub Arc<T>);
                    impl<
                        T: BiddingService,
                    > tonic::server::UnaryService<super::MustWinBlockParams>
                    for MustWinBlockSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MustWinBlockParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::must_win_block(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MustWinBlockSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bidding_service.BiddingService/UpdateNewLandedBlocksDetected" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateNewLandedBlocksDetectedSvc<T: BiddingService>(
                        pub Arc<T>,
                    );
                    impl<
                        T: BiddingService,
                    > tonic::server::UnaryService<super::LandedBlocksParams>
                    for UpdateNewLandedBlocksDetectedSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LandedBlocksParams>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::update_new_landed_blocks_detected(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateNewLandedBlocksDetectedSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bidding_service.BiddingService/UpdateFailedReadingNewLandedBlocks" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateFailedReadingNewLandedBlocksSvc<T: BiddingService>(
                        pub Arc<T>,
                    );
                    impl<T: BiddingService> tonic::server::UnaryService<super::Empty>
                    for UpdateFailedReadingNewLandedBlocksSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as BiddingService>::update_failed_reading_new_landed_blocks(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateFailedReadingNewLandedBlocksSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for BiddingServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "bidding_service.BiddingService";
    impl<T> tonic::server::NamedService for BiddingServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
