log_level = "info,rbuilder=debug"

chain = "mainnet"
reth_datadir = "/mnt/data/reth"

backtest_fetch_eth_rpc_url = "http://127.0.0.1:8545"
backtest_fetch_eth_rpc_parallel = 400
backtest_fetch_output_file = "~/.rbuilder/backtest/main.sqlite"
backtest_fetch_mempool_data_dir = "~/.rbuilder/mempool-data"

backtest_builders = ["mp-ordering", "mgp-ordering"]

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "parallel"
algo = "parallel-builder"
discard_txs = true
num_threads = 25
safe_sorting_only = false

[[ace_protocols]]
# Contract address serves as unique identifier for this ACE protocol
contract_address = "0x0000000aa232009084Bd71A5797d089AA4Edfad4"
from_addresses = [
    "0xc41ae140ca9b281d8a1dc254c50e446019517d04",
    "0xd437f3372f3add2c2bc3245e6bd6f9c202e61bb3",
    "0x693ca5c6852a7d212dabc98b28e15257465c11f3",
]
to_addresses = ["0x0000000aa232009084Bd71A5797d089AA4Edfad4"]
# _lastBlockUpdated storage slot (slot 3)
detection_slots = ["0x0000000000000000000000000000000000000000000000000000000000000003"]
# unlockWithEmptyAttestation(address,bytes) nonpayable
unlock_signatures = ["0x1828e0e7"]
# execute(bytes) nonpayable
force_signatures = ["0x09c5eabe"]